name: SaveStopper
author: Robert 'Bobby' Zenz

main: org.bonsaimind.bukkitplugins.savestopper.Plugin
version: 0.10

commands:
  savestopper:
    description: Main command.
    usage: /<command> [check|save-off|save-on|start|status|stop]