name: SaveStopper
author: Robert 'Bobby' Zenz

main: org.bonsaimind.bukkitplugins.savestopper.Plugin
version: 0.11

commands:
  savestopper:
    description: Control the behavior of SaveStopper.
    usage: /<command> [check|save-off|save-on|start|status|stop]