name: SimpleCronClone
authors: [Robert 'Bobby' Zenz, Eric 'admalledd' Driggers]

main: org.bonsaimind.bukkitplugins.simplecronclone.Plugin
version: 0.8

commands:
  simplecronclone:
    description: Main command.
    usage: /<command> [exec|restart|stop]
