name: SimpleCronClone
author: Robert 'Bobby' Zenz

main: org.bonsaimind.bukkitplugins.simplecronclone.Plugin
version: 0.6

commands:
  simplecronclone:
    description: Main command.
    usage: /<command> [exec|restart|stop]