name: GhostBuster
author: Robert 'Bobby' Zenz

main: org.bonsaimind.bukkitplugins.GhostBuster
version: 0.5

commands:
  ghostbuster:
    description: Main command.
    usage: /<command> [ban|except|info|reload|unban|unban_all|unexcept] [PLAYERNAME]